"""initial schema with RLS

Creates the full Munsiq schema and locks it down with Row-Level Security.

Three things here are hand-written rather than autogenerated, and all three are
load-bearing:

1. The extension and enum prologue. Enums are declared create_type=False in the
   models so that exactly one place creates them; member_role is used by two
   tables and would otherwise be created twice.

2. The four explicit indexes the execution plan calls for, including a partial
   index on corrected fields.

3. The RLS block. It is applied in a LOOP over a table list derived from the
   ORM metadata, not written out per table, so it cannot drift as tables are
   added. Every org-scoped table gets ENABLE *and* FORCE ROW LEVEL SECURITY.

   FORCE matters and is not optional here: a table's owner bypasses RLS by
   default, and Alembic creates these tables as `postgres`. Without FORCE, a
   policy would exist and be silently ignored for the very role the application
   connects as. See docs/db.md.

The revision identifiers are declared below.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "39aa6af426e4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Kept in sync with app.db.models.org_scoped_tables(); tests/test_rls.py asserts
# the two agree, so adding a model without adding it here fails the suite.
ORG_SCOPED_TABLES = [
    "annotations",
    "approvals",
    "audit_log",
    "document_parts",
    "documents",
    "eval_sets",
    "exports",
    "extracted_fields",
    "extraction_schemas",
    "field_corrections",
    "ground_truth_fields",
    "memberships",
    "pages",
    "queues",
    "validation_results",
    "vendors",
    "workflow_steps",
]

ENUM_TYPES = [
    ("member_role", ["owner", "admin", "approver", "reviewer", "viewer"]),
    ("automation_level", ["never", "confident", "always"]),
    ("document_source", ["email", "api", "upload", "sftp"]),
    (
        "annotation_status",
        [
            "importing",
            "processing",
            "to_review",
            "reviewing",
            "confirmed",
            "approved",
            "exporting",
            "exported",
            "rejected",
            "failed",
        ],
    ),
    ("correction_action", ["edit", "delete", "add", "rebox"]),
    ("severity", ["info", "warning", "error"]),
    ("approval_decision", ["pending", "approved", "rejected"]),
]


def upgrade() -> None:
    # ------------------------------------------------------------------ #
    # Extensions
    # ------------------------------------------------------------------ #
    # pgcrypto -> gen_random_uuid() for every primary key.
    # citext   -> case-insensitive users.email, so Ali@x.com == ali@x.com.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ------------------------------------------------------------------ #
    # Enum types — created once, here, because the models declare them
    # create_type=False. member_role is referenced by two tables.
    # ------------------------------------------------------------------ #
    for type_name, values in ENUM_TYPES:
        rendered = ", ".join(f"'{v}'" for v in values)
        op.execute(
            f"DO $$ BEGIN "
            f"IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = '{type_name}') THEN "
            f"CREATE TYPE {type_name} AS ENUM ({rendered}); "
            f"END IF; END $$;"
        )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("vat_number", sa.Text(), nullable=True),
        sa.Column("data_region", sa.Text(), server_default=sa.text("'ksa-dammam'"), nullable=False),
        sa.Column("retention_days", sa.Integer(), server_default=sa.text("365"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("locale", sa.Text(), server_default=sa.text("'ar-SA'"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_log_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_audit_log_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_org_id"), "audit_log", ["org_id"], unique=False)
    op.create_table(
        "eval_sets",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("frozen_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_eval_sets_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_eval_sets")),
    )
    op.create_index(op.f("ix_eval_sets_org_id"), "eval_sets", ["org_id"], unique=False)
    op.create_table(
        "memberships",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "owner",
                "admin",
                "approver",
                "reviewer",
                "viewer",
                name="member_role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("org_id", "user_id", name=op.f("pk_memberships")),
    )
    op.create_table(
        "queues",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "automation_level",
            postgresql.ENUM(
                "never", "confident", "always", name="automation_level", create_type=False
            ),
            server_default=sa.text("'confident'"),
            nullable=False,
        ),
        sa.Column("active_schema_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_queues_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_queues")),
    )
    op.create_index(op.f("ix_queues_org_id"), "queues", ["org_id"], unique=False)
    op.create_table(
        "vendors",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("trn", sa.Text(), nullable=True),
        sa.Column("name_ar", sa.Text(), nullable=True),
        sa.Column("name_en", sa.Text(), nullable=True),
        sa.Column(
            "known_values",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_vendors_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vendors")),
        sa.UniqueConstraint("org_id", "trn", name=op.f("uq_vendors_org_id_trn")),
    )
    op.create_index(op.f("ix_vendors_org_id"), "vendors", ["org_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("queue_id", sa.UUID(), nullable=True),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("sha256", sa.LargeBinary(), nullable=True),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column(
            "source",
            postgresql.ENUM(
                "email", "api", "upload", "sftp", name="document_source", create_type=False
            ),
            nullable=True,
        ),
        sa.Column(
            "has_embedded_ubl", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("embedded_ubl_key", sa.Text(), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("purge_after", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_documents_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queues.id"],
            name=op.f("fk_documents_queue_id_queues"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_documents_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("org_id", "sha256", name=op.f("uq_documents_org_id_sha256")),
    )
    op.create_index(op.f("ix_documents_org_id"), "documents", ["org_id"], unique=False)
    op.create_table(
        "extraction_schemas",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("queue_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "definition",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_extraction_schemas_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queues.id"],
            name=op.f("fk_extraction_schemas_queue_id_queues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extraction_schemas")),
        sa.UniqueConstraint(
            "queue_id", "version", name=op.f("uq_extraction_schemas_queue_id_version")
        ),
    )
    op.create_index(
        op.f("ix_extraction_schemas_org_id"), "extraction_schemas", ["org_id"], unique=False
    )
    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("queue_id", sa.UUID(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("condition", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "approver_role",
            postgresql.ENUM(
                "owner",
                "admin",
                "approver",
                "reviewer",
                "viewer",
                name="member_role",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("approver_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approver_user_id"],
            ["users.id"],
            name=op.f("fk_workflow_steps_approver_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_workflow_steps_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["queue_id"],
            ["queues.id"],
            name=op.f("fk_workflow_steps_queue_id_queues"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_steps")),
    )
    op.create_index(op.f("ix_workflow_steps_org_id"), "workflow_steps", ["org_id"], unique=False)
    op.create_table(
        "document_parts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("part_index", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.Text(), nullable=True),
        sa.Column("doc_type_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("classifier_source", sa.Text(), nullable=True),
        sa.Column("page_start", sa.Integer(), nullable=True),
        sa.Column("page_end", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_parts_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_document_parts_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_parts")),
        sa.UniqueConstraint(
            "document_id", "part_index", name=op.f("uq_document_parts_document_id_part_index")
        ),
    )
    op.create_index(op.f("ix_document_parts_org_id"), "document_parts", ["org_id"], unique=False)
    op.create_table(
        "ground_truth_fields",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("eval_set_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("field_key", sa.Text(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=True),
        sa.Column("expected_value", sa.Text(), nullable=True),
        sa.Column("expected_bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_ground_truth_fields_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["eval_set_id"],
            ["eval_sets.id"],
            name=op.f("fk_ground_truth_fields_eval_set_id_eval_sets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_ground_truth_fields_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ground_truth_fields")),
        sa.UniqueConstraint(
            "eval_set_id",
            "document_id",
            "field_key",
            "row_index",
            name=op.f("uq_ground_truth_fields_eval_set_id_document_id_field_key_row_index"),
        ),
    )
    op.create_index(
        op.f("ix_ground_truth_fields_org_id"), "ground_truth_fields", ["org_id"], unique=False
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("image_key", sa.Text(), nullable=True),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("ocr_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_pages_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_pages_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint(
            "document_id", "page_number", name=op.f("uq_pages_document_id_page_number")
        ),
    )
    op.create_index(op.f("ix_pages_org_id"), "pages", ["org_id"], unique=False)
    op.create_table(
        "annotations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("part_id", sa.UUID(), nullable=False),
        sa.Column("schema_id", sa.UUID(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "importing",
                "processing",
                "to_review",
                "reviewing",
                "confirmed",
                "approved",
                "exporting",
                "exported",
                "rejected",
                "failed",
                name="annotation_status",
                create_type=False,
            ),
            server_default=sa.text("'importing'"),
            nullable=False,
        ),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("vendor_id", sa.UUID(), nullable=True),
        sa.Column("automated", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "blockers", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("assigned_to", sa.UUID(), nullable=True),
        sa.Column("confirmed_by", sa.UUID(), nullable=True),
        sa.Column("confirmed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
            name=op.f("fk_annotations_assigned_to_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by"],
            ["users.id"],
            name=op.f("fk_annotations_confirmed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_annotations_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_annotations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["document_parts.id"],
            name=op.f("fk_annotations_part_id_document_parts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schema_id"],
            ["extraction_schemas.id"],
            name=op.f("fk_annotations_schema_id_extraction_schemas"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendors.id"],
            name=op.f("fk_annotations_vendor_id_vendors"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_annotations")),
    )
    op.create_index(op.f("ix_annotations_org_id"), "annotations", ["org_id"], unique=False)
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("annotation_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.UUID(), nullable=True),
        sa.Column(
            "decision",
            postgresql.ENUM(
                "pending", "approved", "rejected", name="approval_decision", create_type=False
            ),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("decided_by", sa.UUID(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("decided_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_approvals_annotation_id_annotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["decided_by"],
            ["users.id"],
            name=op.f("fk_approvals_decided_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_approvals_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["step_id"],
            ["workflow_steps.id"],
            name=op.f("fk_approvals_step_id_workflow_steps"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_index(op.f("ix_approvals_org_id"), "approvals", ["org_id"], unique=False)
    op.create_table(
        "exports",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("annotation_id", sa.UUID(), nullable=False),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_exports_annotation_id_annotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_exports_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
    )
    op.create_index(op.f("ix_exports_org_id"), "exports", ["org_id"], unique=False)
    op.create_table(
        "extracted_fields",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("annotation_id", sa.UUID(), nullable=False),
        sa.Column("field_key", sa.Text(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=True),
        sa.Column("value_extracted", sa.Text(), nullable=True),
        sa.Column("value_final", sa.Text(), nullable=True),
        sa.Column("value_normalized", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("source", sa.Text(), nullable=True),
        sa.Column("validation_state", sa.Text(), nullable=True),
        sa.Column("bbox", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_extracted_fields_annotation_id_annotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_extracted_fields_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_fields")),
        sa.UniqueConstraint(
            "annotation_id",
            "field_key",
            "row_index",
            name=op.f("uq_extracted_fields_annotation_id_field_key_row_index"),
        ),
    )
    op.create_index(
        op.f("ix_extracted_fields_org_id"), "extracted_fields", ["org_id"], unique=False
    )
    op.create_table(
        "field_corrections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("annotation_id", sa.UUID(), nullable=False),
        sa.Column("field_key", sa.Text(), nullable=False),
        sa.Column("row_index", sa.Integer(), nullable=True),
        sa.Column("old_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "action",
            postgresql.ENUM(
                "edit", "delete", "add", "rebox", name="correction_action", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_field_corrections_annotation_id_annotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_field_corrections_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_field_corrections_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_corrections")),
    )
    op.create_index(
        op.f("ix_field_corrections_org_id"), "field_corrections", ["org_id"], unique=False
    )
    op.create_table(
        "validation_results",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("annotation_id", sa.UUID(), nullable=False),
        sa.Column("rule_code", sa.Text(), nullable=False),
        sa.Column(
            "severity",
            postgresql.ENUM("info", "warning", "error", name="severity", create_type=False),
            nullable=False,
        ),
        sa.Column("message_ar", sa.Text(), nullable=True),
        sa.Column("message_en", sa.Text(), nullable=True),
        sa.Column("field_key", sa.Text(), nullable=True),
        sa.Column("passed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["annotation_id"],
            ["annotations.id"],
            name=op.f("fk_validation_results_annotation_id_annotations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_validation_results_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_results")),
    )
    op.create_index(
        op.f("ix_validation_results_org_id"), "validation_results", ["org_id"], unique=False
    )

    # ------------------------------------------------------------------ #
    # Indexes the plan calls for explicitly
    # ------------------------------------------------------------------ #
    op.create_index(
        "ix_annotations_org_status_created",
        "annotations",
        ["org_id", "status", sa.text("created_at DESC")],
    )
    op.create_index(
        "ix_documents_org_created",
        "documents",
        ["org_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "ix_field_corrections_org_field_created",
        "field_corrections",
        ["org_id", "field_key", sa.text("created_at DESC")],
    )
    # Partial index: only rows a human actually changed. This is the query that
    # drives the correction-rate metric, and the partial predicate keeps the
    # index proportional to the error rate rather than to the table.
    op.create_index(
        "ix_extracted_fields_org_field_corrected",
        "extracted_fields",
        ["org_id", "field_key"],
        postgresql_where=sa.text("value_final IS DISTINCT FROM value_extracted"),
    )

    # ------------------------------------------------------------------ #
    # Row-Level Security
    # ------------------------------------------------------------------ #
    # Applied in a loop so it cannot drift from the table list. ENABLE turns
    # policies on; FORCE makes them apply to the table OWNER as well, which is
    # the account migrations and the app both run as. Without FORCE this whole
    # block would be decorative.
    for table in ORG_SCOPED_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY {table}_org_isolation ON {table} "
            f"USING (org_id = current_setting('app.current_org_id', true)::uuid) "
            f"WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid)"
        )

    # organizations is isolated on its own primary key: it has no org_id, but
    # leaking the tenant list is still a leak.
    op.execute("ALTER TABLE organizations ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE organizations FORCE ROW LEVEL SECURITY")
    op.execute(
        "CREATE POLICY organizations_org_isolation ON organizations "
        "USING (id = current_setting('app.current_org_id', true)::uuid) "
        "WITH CHECK (id = current_setting('app.current_org_id', true)::uuid)"
    )

    # users is deliberately NOT org-scoped — one person may belong to several
    # organizations, and membership is what binds them. See docs/db.md.

    # Read access for the non-bypassing roles the isolation test runs under.
    # No policy is granted here; RLS still filters every row they can see.
    for table in [*ORG_SCOPED_TABLES, "organizations", "users"]:
        op.execute(f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table} TO authenticated")


def downgrade() -> None:
    for table in [*ORG_SCOPED_TABLES, "organizations"]:
        op.execute(f"DROP POLICY IF EXISTS {table}_org_isolation ON {table}")
    op.drop_index(op.f("ix_validation_results_org_id"), table_name="validation_results")
    op.drop_table("validation_results")
    op.drop_index(op.f("ix_field_corrections_org_id"), table_name="field_corrections")
    op.drop_table("field_corrections")
    op.drop_index(op.f("ix_extracted_fields_org_id"), table_name="extracted_fields")
    op.drop_table("extracted_fields")
    op.drop_index(op.f("ix_exports_org_id"), table_name="exports")
    op.drop_table("exports")
    op.drop_index(op.f("ix_approvals_org_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_annotations_org_id"), table_name="annotations")
    op.drop_table("annotations")
    op.drop_index(op.f("ix_pages_org_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_ground_truth_fields_org_id"), table_name="ground_truth_fields")
    op.drop_table("ground_truth_fields")
    op.drop_index(op.f("ix_document_parts_org_id"), table_name="document_parts")
    op.drop_table("document_parts")
    op.drop_index(op.f("ix_workflow_steps_org_id"), table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_index(op.f("ix_extraction_schemas_org_id"), table_name="extraction_schemas")
    op.drop_table("extraction_schemas")
    op.drop_index(op.f("ix_documents_org_id"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_vendors_org_id"), table_name="vendors")
    op.drop_table("vendors")
    op.drop_index(op.f("ix_queues_org_id"), table_name="queues")
    op.drop_table("queues")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_eval_sets_org_id"), table_name="eval_sets")
    op.drop_table("eval_sets")
    op.drop_index(op.f("ix_audit_log_org_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("users")
    op.drop_table("organizations")

    for type_name, _ in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
