"""add pages.text_source

Revision ID: 75484fbb7214
Revises: 39aa6af426e4
Create Date: 2026-09-07 16:35:29.411404
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "75484fbb7214"
down_revision: str | None = "39aa6af426e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("text_source", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "text_source")
    # ### end Alembic commands ###
